export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_FAILURE = "CREATE_CART_FAILURE";

export const GET_ALL_CART_ITEMS_REQUEST = "GET_ALL_CART_ITEMS_REQUEST";
export const GET_ALL_CART_ITEMS_SUCCESS = "GET_ALL_CART_ITEMS_SUCCESS";
export const GET_ALL_CART_ITEMS_FAILURE = "GET_ALL_CART_ITEMS_FAILURE";

export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAILURE = "ADD_ITEM_TO_CART_FAILURE";

export const UPDATE_CARTITEM_QUANTITY_REQUEST =
  "UPDATE_CARTITEM_QUANTITY_REQUEST";
export const UPDATE_CARTITEM_QUANTITY_SUCCESS =
  "UPDATE_CARTITEM_QUANTITY_SUCCESS";
export const UPDATE_CARTITEM_QUANTITY_FAILURE =
  "UPDATE_CARTITEM_QUANTITY_FAILURE";

export const REMOVE_CARTITEM_FROM_CART_REQUEST =
  "REMOVE_CARTITEM_FROM_CART_REQUEST";
export const REMOVE_CARTITEM_FROM_CART_SUCCESS =
  "REMOVE_CARTITEM_FROM_CART_SUCCESS";
export const REMOVE_CARTITEM_FROM_CART_FAILURE =
  "REMOVE_CARTITEM_FROM_CART_FAILURE";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE";
