export const CREATE_INGREDIENT_REQUEST = "CREATE_INGREDIENT_REQUEST";
export const CREATE_INGREDIENT_SUCCESS = "CREATE_INGREDIENT_SUCCESS";
export const CREATE_INGREDIENT_FAILURE = "CREATE_INGREDIENT_FAILURE";

export const CREATE_INGREDIENT_CATEGORY_REQUEST =
  "CREATE_INGREDIENT_CATEGORY_REQUEST";
export const CREATE_INGREDIENT_CATEGORY_SUCCESS =
  "CREATE_INGREDIENT_CATEGORY_SUCCESS";
export const CREATE_INGREDIENT_CATEGORY_FAILURE =
  "CREATE_INGREDIENT_CATEGORY_FAILURE";

export const GET_INGREDIENT_BY_RESTAURANT_ID_REQUEST =
  "GET_INGREDIENT_BY_RESTAURANT_ID_REQUEST";
export const GET_INGREDIENT_BY_RESTAURANT_ID_SUCCESS =
  "GET_INGREDIENT_BY_RESTAURANT_ID_SUCCESS";
export const GET_INGREDIENT_BY_RESTAURANT_ID_FAILURE =
  "GET_INGREDIENT_BY_RESTAURANT_ID_FAILURE";

export const GET_INGREDIENT_CATEGORY_BY_RESTAURANT_ID_REQUEST =
  "GET_INGREDIENT_CATEGORY_BY_RESTAURANT_ID_REQUEST";
export const GET_INGREDIENT_CATEGORY_BY_RESTAURANT_ID_SUCCESS =
  "GET_INGREDIENT_CATEGORY_BY_RESTAURANT_ID_SUCCESS";
export const GET_INGREDIENT_CATEGORY_BY_RESTAURANT_ID_FAILURE =
  "GET_INGREDIENT_CATEGORY_BY_RESTAURANT_ID_FAILURE";

export const GET_INGREDIENT_CATEGORY_BY_ID_REQUEST =
  "GET_INGREDIENT_CATEGORY_BY_ID_REQUEST";
export const GET_INGREDIENT_CATEGORY_BY_ID_SUCCESS =
  "GET_INGREDIENT_CATEGORY_BY_ID_SUCCESS";
export const GET_INGREDIENT_CATEGORY_BY_ID_FAILURE =
  "GET_INGREDIENT_CATEGORY_BY_ID_FAILURE";

export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAILURE = "UPDATE_STOCK_FAILURE";
